version: '3.1'

services: 
  reverse-proxy:
    image: nginx:1.17.6-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports: 
      - 80:80
    restart: always
    environment:
      - NGINX_HOST=52.78.35.26
      - NGINS_PORT=80

  jenkins:
    image: jenkins/jenkins:lts
    volumes:
      - ./jenkins/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8080:8080
      - 5000:5000
      - 50000:50000
    restart: always
    user: root
    environment:
      - TZ="Asia/Seoul"
