version: '3.1'

services: 
  reverse-proxy:
    image: nginx:1.17.6-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /var/bun/docker.sock:/tmp/docker.sock:ro
    ports: 
      - 80:80
    restart: always

  jenkins:
    image: jenkins/jenkins:lts
    volumes:
      - ./jenkins/jenkins_home:/var/jenkins_home
